### ISSUE TITLE
Unable to find imports in the code!

### ISSUE THREAD

**Issue by naveenselvan** [OALabs/PyIATRebuild#5]
I am getting below error!
WARNING: warning null reldesc
Traceback (most recent call last):
  File "pyiatrebuild.py", line 652, in <module>
    main()
  File "pyiatrebuild.py", line 644, in main
    new_pe_data = rebuild_iat(args.in_pid, pe_data, args.in_base_address, args.in_oep)
  File "pyiatrebuild.py", line 245, in rebuild_iat
    imp_table = reslove_iat_pointers(pid, iat_ptrs)
  File "pyiatrebuild.py", line 169, in reslove_iat_pointers
    assert len(imp_table) != 0, "Unable to find imports in code!"
AssertionError: Unable to find imports in code!

**Comment by assaflerman** [comment]
Had the same problem. Tried it on a Windows 7 x32 and it worked. I didn't get the chance to dig into the script, but maybe it doesn't support 64 bit address space for some reason.
